// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
/** Legacy anon JWT (eyJ...) — required for reliable auth with @supabase/supabase-js */
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

const supabaseKey = SUPABASE_ANON_KEY || SUPABASE_PUBLISHABLE_KEY;

if (import.meta.env.DEV && (!SUPABASE_URL || !supabaseKey)) {
  console.error(
    '[UniHub] Missing VITE_SUPABASE_URL or a key. Set VITE_SUPABASE_ANON_KEY (from Supabase → Settings → API → anon public) or VITE_SUPABASE_PUBLISHABLE_KEY in .env'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL ?? '', supabaseKey ?? '', {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});