// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
/** Legacy anon JWT is still supported for local development. */
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

const supabaseKey = SUPABASE_ANON_KEY || SUPABASE_PUBLISHABLE_KEY;
export const isSupabaseConfigured = Boolean(SUPABASE_URL && supabaseKey);

type SupabaseLikeError = {
  message: string;
  status?: number;
  code?: string;
};

const createMissingConfigError = (operation: string): SupabaseLikeError => ({
  message: `[UniHub] Supabase is not configured. ${operation}. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY (or VITE_SUPABASE_PUBLISHABLE_KEY) to your local .env file.`,
  status: 503,
  code: 'supabase_missing_config',
});

const missingConfigError = createMissingConfigError('This feature is unavailable');

const createChainStub = (result: { data: unknown; error: SupabaseLikeError | null; count?: number }) => {
  const proxyTarget = () => undefined;

  return new Proxy(proxyTarget as unknown as object, {
    get(_target, prop) {
      if (prop === 'then') {
        return (onFulfilled?: (value: typeof result) => unknown, onRejected?: (reason: unknown) => unknown) =>
          Promise.resolve(result).then(onFulfilled, onRejected);
      }

      if (prop === 'catch') {
        return (onRejected?: (reason: unknown) => unknown) => Promise.resolve(result).catch(onRejected);
      }

      if (prop === 'finally') {
        return (onFinally?: () => void) => Promise.resolve(result).finally(onFinally);
      }

      return (..._args: unknown[]) => createChainStub(result);
    },
    apply() {
      return createChainStub(result);
    },
  });
};

const createStorageBucketStub = (bucket: string) => ({
  upload: async () => ({ data: null, error: createMissingConfigError(`Upload to storage bucket "${bucket}"`) }),
  createSignedUrl: async () => ({ data: null, error: createMissingConfigError(`Create a signed URL in storage bucket "${bucket}"`) }),
  list: async () => ({ data: [], error: createMissingConfigError(`List files in storage bucket "${bucket}"`) }),
  remove: async () => ({ data: null, error: createMissingConfigError(`Remove files from storage bucket "${bucket}"`) }),
  getPublicUrl: () => ({
    data: { publicUrl: '' },
    error: createMissingConfigError(`Read a public URL from storage bucket "${bucket}"`),
  }),
});

const createChannelStub = (name: string) => ({
  subscribe: () => createChannelStub(name),
  on: () => createChannelStub(name),
  track: async () => ({ error: createMissingConfigError(`Track realtime channel "${name}"`) }),
  untrack: async () => ({ error: createMissingConfigError(`Untrack realtime channel "${name}"`) }),
  send: async () => ({ error: createMissingConfigError(`Send on realtime channel "${name}"`) }),
  unsubscribe: async () => ({ error: createMissingConfigError(`Unsubscribe realtime channel "${name}"`) }),
});

const createFallbackClient = (): SupabaseClient<Database> => {
  const client = {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      signInWithPassword: async () => ({ data: { user: null, session: null }, error: createMissingConfigError('Sign in') }),
      signOut: async () => ({ error: null }),
      updateUser: async () => ({ data: { user: null }, error: createMissingConfigError('Update the current user') }),
      resetPasswordForEmail: async () => ({ data: null, error: createMissingConfigError('Send a password reset email') }),
      onAuthStateChange: (callback: (event: string, session: null) => void) => {
        queueMicrotask(() => callback('INITIAL_SESSION', null));
        return { data: { subscription: { unsubscribe: () => {} } } };
      },
    },
    from: (_table: string) => createChainStub({ data: [], error: missingConfigError, count: 0 }),
    storage: {
      from: (bucket: string) => createStorageBucketStub(bucket),
    },
    rpc: async (fn: string) => ({ data: null, error: createMissingConfigError(`Run RPC function "${fn}"`) }),
    channel: (name: string) => createChannelStub(name),
    removeChannel: async (channel: unknown) => channel,
    functions: {
      invoke: async (fn: string) => ({ data: null, error: createMissingConfigError(`Invoke edge function "${fn}"`) }),
    },
  } as unknown as SupabaseClient<Database>;

  return client;
};

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL!, supabaseKey!, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createFallbackClient();

if (!isSupabaseConfigured) {
  console.warn(
    '[UniHub] Supabase environment variables are missing. Create a local .env file with VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY (or VITE_SUPABASE_PUBLISHABLE_KEY) to enable backend features.'
  );
}
